services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user_subscriptions'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d user_subscriptions" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend
networks:
  backend:
    driver: bridge